language: c
dist: xenial

addons:
    apt:
        sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:savoury1/backports
            - sourceline: ppa:savoury1/apt-xenial
            - sourceline: ppa:savoury1/build-tools
        update: true
        packages:
            - cmake
            - cppcheck
            - patch
            - ninja-build

branches:
      except:
          - /^nightly$/

cache:
    directories:
        - $VITASDK
        - $HOME/opt

before_script:
    - travis_wait bash .travis.d/install_toolchain.sh

script:
    - cppcheck --error-exitcode=1 --enable=style,performance,portability src/*.c
    - mkdir build
    - /usr/bin/cmake --version
    - cd build && /usr/bin/cmake -GNinja .. && ninja

before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git tag -f nightly
    - git push -q https://$TAGPERM@github.com/$TRAVIS_REPO_SLUG -f --tags

deploy:
    provider: releases
    api_key: $GH_TOKEN
    file:
        - $TRAVIS_BUILD_DIR/build/savemgr.vpk
    overwrite: true
    skip_cleanup: true
    on:
        tags: false
        branch: master

after_deploy:
    - bash $TRAVIS_BUILD_DIR/.travis.d/deploy_nightly.sh
